### ISSUE TITLE
"FATA Immich Url is missing" if config has duplicate entries

### ISSUE THREAD

**Issue by desmond206x** [damongolding/immich-kiosk#112]
After a config migration to your template here (I started some versions ago) my immich-kiosk docker won't start correctly.

The log says only "immich-kiosk  | 2024/10/08 22:10:29 FATA Immich Url is missing" and the container restarts.

**I found out, that I had a duplicate entry "show_time: true" in my config.**

So maybe we need a better error logging if the config is corrupt.

**Screenshots**
![image](https://github.com/user-attachments/assets/2ff8c608-60de-4298-8e39-8240f6a48266)

**Your Kiosk version**
0.11.1

**Your Kiosk installation**
- Docker

**Comment by desmond206x** [comment]
Maybe move this part to another bug ticket if you like.

You get this in the web if you use your config example from https://github.com/damongolding/immich-kiosk/blob/main/config.example.yaml

![image](https://github.com/user-attachments/assets/e0f0088e-4f10-4967-9e82-94ac125ed02c)

The person and album `- ""` are invalid if not commented out.

If I comment the unneded one, all works fine again.

**Comment by damongolding** [comment]
Someone else ran into this issue too. Some better error logging is definitely needed.

**Comment by damongolding** [comment]
Should be fixed in 0.11.2 but if you want to test it now you can pull the `damongolding/immich-kiosk-development:0.11.2-beta.3` image

**Comment by damongolding** [comment]
fixed in 0.11.2
