### ISSUE TITLE
Error retrieving image after Immich V1.118.1 update

### ISSUE THREAD

**Issue by stantyan** [damongolding/immich-kiosk#139]
**Describe the bug**
After Immich V1.118.1 update Immich Kiosk stopped working with the following error:
`2024-10-16T07:39:36.470325614Z 10:39:36 ERRO Couldn't read error body="" url="http://domain.com/api/search/random?size=1000&type=IMAGE&withExif=true"
2024-10-16T07:39:36.470331536Z 10:39:36 ERRO retrieving image err="selecting image: unexpected status code: 404"
2024-10-16T07:39:36.660357379Z 10:39:36 ERRO unexpected status code: 404
2024-10-16T07:39:36.660380694Z 10:39:36 ERRO unexpected status code: 404
2024-10-16T07:39:36.660400742Z 10:39:36 ERRO Couldn't read error body="" url="http://domain.com/api/search/random?size=1000&type=IMAGE&withExif=true"
2024-10-16T07:39:36.660404599Z 10:39:36 ERRO retrieving image err="selecting image: unexpected status code: 404"
2024-10-16T07:39:48.077508593Z 10:39:48 ERRO unexpected status code: 404
2024-10-16T07:39:48.077543240Z 10:39:48 ERRO unexpected status code: 404`

**To Reproduce**
Update Immich to V1.118.1

**Screenshots**
![screenshot-2024-10-16-10-44-00@2x](https://github.com/user-attachments/assets/b03409f6-3774-40b6-86c1-e6dffb32e4cb)

**Your Kiosk version**
v0.11.3
Latest

**Your Kiosk installation**
- Docker

**Your Kiosk ENV or config file**
TZ=Europe/Berlin
KIOSK_IMMICH_API_KEY=XXXXXXXXXXXXXXXXXX
KIOSK_IMMICH_URL=domain.com
KIOSK_SHOW_TIME=TRUE
KIOSK_TIME_FORMAT=24
KIOSK_SHOW_DATE=TRUE
KIOSK_DATE_FORMAT=DD MMMM YYYY
KIOSK_REFRESH=10
KIOSK_DISABLE_SCREENSAVER=TRUE
KIOSK_SHOW_ARCHIVED=FALSE
KIOSK_DISABLE_UI=FALSE
KIOSK_HIDE_CURSOR=FALSE
KIOSK_FONT_SIZE=120
KIOSK_BACKGROUND_BLUR=TRUE
KIOSK_THEME=FADE
KIOSK_LAYOUT=single
KIOSK_TRANSITION=NONE
KIOSK_FADE_TRANSITION_DURATION=1
KIOSK_CROSS_FADE_TRANSITION_DURATION=1
KIOSK_SHOW_PROGRESS=FALSE
KIOSK_IMAGE_FIT=CONTAIN
KIOSK_SHOW_IMAGE_TIME=FALSE
KIOSK_IMAGE_TIME_FORMAT=24
KIOSK_SHOW_IMAGE_DATE=TRUE
KIOSK_IMAGE_DATE_FORMAT=DD MMMM YYYY
KIOSK_SHOW_IMAGE_EXIF=FALSE
KIOSK_SHOW_IMAGE_LOCATION=TRUE
KIOSK_PASSWORD=
KIOSK_CACHE=TRUE
KIOSK_PREFETCH=TRUE
KIOSK_ASSET_WEIGHTING=TRUE

**Desktop:**
 - OS: macOS
 - Browser: Chrome, Safari

**Comment by damongolding** [comment]
Are you still able to access the Immich frontend ok and are your asset visible if you can? 

Sometimes I have to docker down and up Immich but I think that's because i manly use external libraries.

**Comment by stantyan** [comment]
Yes, Immich is functioning as expected, no any issues on the frontend. Could it be because I do not use config files and dump all the config in variables?

**Comment by Chevyray82** [comment]
I am also getting a 404 Error since the update. I have confirmed that my Immich is functioning fine.

**Comment by damongolding** [comment]
Did you updated your Immich compose file as per the release notes?

A 404 would suggest that Kiosk can talk to Immich but the API endpoint has moved or is missing. I saw in Immich 1.118 that the internal port as well as the Redis and Database hash changed.

**Comment by njspix** [comment]
Several API calls have been deprecated; i think this is probably the issue?

https://github.com/immich-app/immich/releases/tag/v1.118.0

**Comment by damongolding** [comment]
> Several API enpoints (including /api/people/:id/assets) have been deprecated; i think this is probably the issue?
> 
> 
> 
> https://github.com/immich-app/immich/releases/tag/v1.118.0

I moved from using those endpoints in 0.11.0, so that shouldn't be the issue.

**Comment by damongolding** [comment]
I can't seem to reproduce this. I got a 400 error but then I realised the personID I was using didn't exist.

**Comment by njspix** [comment]
Ok, sorry for the red herring! Haven’t investigated very far on my end, just say “breaking change“ and assumed that was the problem.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by damongolding** [comment]
> Ok, sorry for the red herring! Haven’t investigated very far on my end, just say “breaking change“ and assumed that was the problem.

No need to apologise! I don't expect people to know the full in and outs of my code and it's a very reasonable assumption.

**Comment by magicman3211** [comment]
Im getting just a blank screen now, nothing in logs, tried on 3 browsers, brave, firefox and safari

**Comment by damongolding** [comment]
> Im getting just a blank screen now, nothing in logs, tried on 3 browsers, brave, firefox and safari

I think you are in sleep mode [https://github.com/damongolding/immich-kiosk?tab=readme-ov-file#sleep-mode](https://github.com/damongolding/immich-kiosk?tab=readme-ov-file#sleep-mode). This not related to this issue.

**Comment by Iktwo** [comment]
I don't know if it helps anyone, but I ran into this, and it was because I was running it alongside my immich server with the local ip, so the kiosk container didn't see the other one. That means it was a docker configuration issue.

I ran this on another device and it worked, so I just need to read on how to configure that access.

**Comment by damongolding** [comment]
> I don't know if it helps anyone, but I ran into this, and it was because I was running it alongside my immich server with the local ip, so the kiosk container didn't see the other one. That means it was a docker configuration issue.
> 
> 
> 
> I ran this on another device and it worked, so I just need to read on how to configure that access.

Someone else had this kind of issue. We bypassed it with `network_mode: host`. I run Kiosk and Immich side by side e.g. `193.168.0.111:2283` `193.168.0.111:3000` but I am unable to reproduce these issues.

**Comment by LaDaniWapa** [comment]
I also get this error on kiosk 0.12.0, it gives me an error saying:
`ERRO Couldn't read error body="" url="https://immich.domain.home/api/search/random?size=1000&type=IMAGE&withExif=true&withPeople=true"`
And it's true, when I get to that url, all i got is an error message, but if I change it to **/api/assets/random**, I get the full json.
Also my immich server is running latests at the momment, 1.119.1

**Comment by LaDaniWapa** [comment]
> I also get this error on kiosk 0.12.0, it gives me an error saying: `ERRO Couldn't read error body="" url="https://immich.domain.home/api/search/random?size=1000&type=IMAGE&withExif=true&withPeople=true"` And it's true, when I get to that url, all i got is an error message, but if I change it to **/api/assets/random**, I get the full json. Also my immich server is running latests at the momment, 1.119.1

My config file was not in the right place lmao, I guess I needed an api key for the search endpoint idk

**Comment by damongolding** [comment]
> > I also get this error on kiosk 0.12.0, it gives me an error saying: `ERRO Couldn't read error body="" url="https://immich.domain.home/api/search/random?size=1000&type=IMAGE&withExif=true&withPeople=true"` And it's true, when I get to that url, all i got is an error message, but if I change it to **/api/assets/random**, I get the full json. Also my immich server is running latests at the momment, 1.119.1
> 
> 
> 
> My config file was not in the right place lmao, I guess I needed an api key for the search endpoint idk

Yes the search endpoint is POST and requires an api key.

**Comment by damongolding** [comment]
@stantyan @Chevyray82 are you still experiencing this issue or have they resolved themselves?

**Comment by Chevyray82** [comment]
I was able to fix mine. Immich needed updating

**Comment by stantyan** [comment]
> @stantyan @Chevyray82 are you still experiencing this issue or have they resolved themselves?

Hi, I only now had a chance to update all the containers to latest versions and I still get this 404 error, however the log messages are now different:

`2024-11-18T18:15:34.127964670Z 20:15:34 ERRO Couldn't read error body="" url="http:///IMMICH.DOMAIN/api/search/random?kiosk=d8549d55d9a2a5df50a3cbe1914b80b4cd83aa52fd1bed47e6a9e4776a89f07f"
2024-11-18T18:15:34.127967766Z 20:15:34 ERRO retrieving image err="selecting image: unexpected status code: 404"
2024-11-18T18:15:40.904919622Z 20:15:40 ERRO unexpected status code: 404
2024-11-18T18:15:40.904946103Z 20:15:40 ERRO unexpected status code: 404
2024-11-18T18:15:40.904949058Z 20:15:40 ERRO Couldn't read error body="" url="http:///IMMICH.DOMAIN/api/search/random?kiosk=2047c11135e2a561a7481f32457231113c70d15c383887269d6464288c93d2f9"
2024-11-18T18:15:40.904952044Z 20:15:40 ERRO retrieving image err="selecting image: unexpected status code: 404"
2024-11-18T18:15:49.150239320Z 20:15:49 ERRO unexpected status code: 404
2024-11-18T18:15:49.150271371Z 20:15:49 ERRO unexpected status code: 404
2024-11-18T18:15:49.150277283Z 20:15:49 ERRO Couldn't read error body="" url="http:///IMMICH.DOMAIN/api/search/random?kiosk=5aecdc40fecc8f860d42556e736e14335fd36a5b93d8488334abd567318e73f7"
2024-11-18T18:15:49.150282593Z 20:15:49 ERRO retrieving image err="selecting image: unexpected status code: 404"
2024-11-18T18:16:04.178927891Z 20:16:04 ERRO unexpected status code: 404
2024-11-18T18:16:04.178990471Z 20:16:04 ERRO unexpected status code: 404
2024-11-18T18:16:04.179002034Z 20:16:04 ERRO Couldn't read error body="" url="http:///IMMICH.DOMAIN/api/search/random?kiosk=aad7a93fd01bfbe196d18083b43deadfb7fcd98c9fc81b8ccf09080e66264641"
2024-11-18T18:16:04.179010079Z 20:16:04 ERRO retrieving image err="selecting image: unexpected status code: 404"
2024-11-18T18:16:19.200494766Z 20:16:19 ERRO unexpected status code: 404
2024-11-18T18:16:19.200529283Z 20:16:19 ERRO unexpected status code: 404
2024-11-18T18:16:19.200549392Z 20:16:19 ERRO Couldn't read error body="" url="http://IMMICH.DOMAIN/api/search/random?kiosk=2047c11135e2a561a7481f32457231113c70d15c383887269d6464288c93d2f9"
2024-11-18T18:16:19.200558389Z 20:16:19 ERRO retrieving image err="selecting image: unexpected status code: 404"`

**Comment by damongolding** [comment]
> 
> Hi, I only now had a chance to update all the containers to latest versions and I still get this 404 error, however the log messages are now different:
> 
> 
> `2024-11-18T18:15:34.127964670Z 20:15:34 ERRO Couldn't read error body="" url="http:///IMMICH.DOMAIN/api/search/random?kiosk=d8549d55d9a2a5df50a3cbe1914b80b4cd83aa52fd1bed47e6a9e4776a89f07f"

The errors are a little different as I updated Kiosk to be a bit more resilient with http requests. 

Could you try limiting the amount of image data Kiosk asks for?

If you use a config.yaml file you can do this by adding the below 👇🏼 

```yaml
kiosk:
  fetched_assets_size: 100
```

And `KIOSK_FETCHED_ASSETS_SIZE` for env.
