### ISSUE TITLE
Cant read albums from immich

### ISSUE THREAD

**Issue by magicman3211** [damongolding/immich-kiosk#141]
my log file from portainer
running immich 1.118.2
![kiosk](https://github.com/user-attachments/assets/8c995d2f-d535-4411-b1f0-b919e258e590)

**Comment by magicman3211** [comment]
I retried 3 times creating new apis in immich

**Comment by damongolding** [comment]
Hey.

You need to use the album ID not the album name e.g. "Sallys Wedding".

You can find the docs for albums here [https://github.com/damongolding/immich-kiosk?tab=readme-ov-file#albums](https://github.com/damongolding/immich-kiosk?tab=readme-ov-file#albums)

**Comment by magicman3211** [comment]
awesome, thank you, fixed
