### ISSUE TITLE
geo location: if no city is provided, the resulting string looks like ', <state/country>...'

### ISSUE THREAD

**Issue by ReSqAr** [damongolding/immich-kiosk#163]
**Describe the bug**

**To Reproduce**
1. Have photos with no city
2. Check it in the Kiosk mode:

<img width="286" alt="image" src="https://github.com/user-attachments/assets/6ef7bf6f-b8eb-4915-a42a-663f41b93c69">

**Expected behavior**

It shouldn't have the comma in front of the state/country.

The comma can be traced to this code:
- https://github.com/damongolding/immich-kiosk/blob/main/views/views_image-metadata.templ#L24
- https://github.com/damongolding/immich-kiosk/blob/main/views/views_image-metadata.templ#L29

**Screenshots**

Provided above

**Your Kiosk version**
This can be found on the startup banner in the terminal. Or in the browser via the `<meta name="version" content={ KioskVersion } />` tag or browser console.

version 0.12.0

**Your Kiosk installation**
- Docker [x]
- Binary

**Your Kiosk ENV or config file**
Please remove any sensitive data first (Immich API and URL)

**Any parms passed to the URL used to access Kiosk**
- http://****/?show_time=true&time_format=12

**Desktop:**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 14.6.1

**Smartphone:**

**Additional context**

**Comment by damongolding** [comment]
Thanks for the bug report. I see the issue and shall patch it 👍🏼
