### ISSUE TITLE
Consecutive commas in rendered location, not in metadata

### ISSUE THREAD

**Issue by pjft** [damongolding/immich-kiosk#174]
**Describe the bug**
Unsure if related to #163 - or a side effect of the fix, but the location has two consecutive commas with a blank space in the middle.

Sorry for the new post during the weekend.

**To Reproduce**
Just launch it with the option to show the location.

**Expected behavior**
Location to show as (city, state, country), but if any is empty, not render a blank space and a comma (if that's what's happening?).

The EXIF metadata returned by Immich is, for instance:
"city":"Dublin","state":"Leinster","country":"Ireland"
"city":"London","state":"England","country":"United Kingdom"

so maybe it's actually just a mistake in the renderer as there's no fourth value.

**Screenshots**
<img width="373" alt="image" src="https://github.com/user-attachments/assets/b1181167-9532-4661-9aea-efa97c5bd0ab">

<img width="347" alt="image" src="https://github.com/user-attachments/assets/273519b2-cf50-47c7-8c50-6a109d991891">

**Your Kiosk version**
damongolding/immich-kiosk-development:0.13.0-beta.1

**Your Kiosk installation**
- Docker

**Comment by damongolding** [comment]
Are you in the production or development release when seeing this?

The fix for #163 hasn't been pushed live yet. It was meant for 0.12.1 which wasn't released. I've rolled it into 0.13.0 instead.

**Comment by pjft** [comment]
I am in the last beta you suggested yesterday. I'll go back to the :latest and see.

EDIT: sorry. Yes, it's fixed in the latest release now, apologies.

My bad.
