### ISSUE TITLE
Full screen black

### ISSUE THREAD

**Issue by zgr0629** [damongolding/immich-kiosk#185]
**Describe the bug**
After upgrading the kiosk to 0.13.0, the home page only displays black when opened.

**To Reproduce**
1. Upgrade kiosk to 0.13.0
2. Open kiosk

**Expected behavior**
Normal display of album.

**Screenshots**

<img width="941" alt="2024-11-16 00 42 26" src="https://github.com/user-attachments/assets/a8ae9e5e-02f5-4fd6-9aa9-adc911fb7dd1">
After opening the homepage, I see the https://xxxxxx/image request (post method). I am not familiar with the immich API, but I tried to right-click this request and click Open in a New Tab, and found that the image can be displayed correctly (get method). 
Is the code for getting image request wrong?

**Your Kiosk version**
0.13.0

**Your Kiosk installation**
- Docker

**Your Kiosk ENV or config file**
Please remove any sensitive data first (Immich API and URL)

**Any parms passed to the URL used to access Kiosk**
- https://xxxxxx/

**Desktop:**
 - Browser chrome

**Additional context**

**Comment by damongolding** [comment]
Do you have sleep mode on? That endpoint only sends 204 while in sleep mode hours.

**Comment by A-wels** [comment]
Sorry for reopening this, but I seem to have a similar issue. I have sleep mode enabled from 22 to 7

```
## Sleep mode
sleep_start: 22 # sleep mode start time
sleep_end: 7 # sleep mode end time
sleep_icon: true
```

However, at 13:04 the sleepmode seems to be enabled.
![grafik](https://github.com/user-attachments/assets/fcbf9f65-62d3-4f7c-b6ae-77d0a4ee2138)
I expect that this is some timezone stuff, since I am in CET.

**Comment by damongolding** [comment]
Hey 👋

Are you changing the time zone in the compose file?

Also I assume you don't have either `sleep_start` or `sleep_end` in your url?

**Comment by A-wels** [comment]
I have neither of those in the url and the time zone is not changed in the compose file (nor is there anything about timezones in my config). 

I'll try to debug it if I have some time. Dont stress about it :)
