### ISSUE TITLE
Default colour for sleep mode text is too dark

### ISSUE THREAD

**Issue by joelis10** [damongolding/immich-kiosk#186]
**Describe the bug**
Likely not a bug and can be fixed with custom CSS, but in my opinion, the default sleep mode text is waaayy too dark. I can barely read it from a distance on my small clock, which is where it would be the most helpful.

**To Reproduce**
1. Add a start and end time for immich-kiosk's sleep mode to your environment variables;
2. Try and read the text at localhost:3000.

**Expected behavior**
Sleep mode text is actually readable somewhat or at least customisable using envrionement variables/custom CSS with docs on which variables/elements need customising.

**Screenshots**
![image](https://github.com/user-attachments/assets/55313977-f76b-4003-b855-6000457434cb)

**Your Kiosk version**
0.13.0

**Your Kiosk installation**
Docker

**Your Kiosk ENV or config file**
```services:
  immich-kiosk-clock:
    image: damongolding/immich-kiosk:latest
    container_name: immich-kiosk-clock
    environment:
      TZ: "Europe/London"
      KIOSK_IMMICH_API_KEY: ""
      KIOSK_IMMICH_URL: "http://192.168.1.0:2283"
      KIOSK_DISABLE_UI: FALSE
      KIOSK_SHOW_DATE: TRUE
      KIOSK_DATE_FORMAT: DDD DD MMM YYYY
      KIOSK_SHOW_TIME: TRUE
      KIOSK_TIME_FORMAT: 24
      KIOSK_REFRESH: 60
      KIOSK_ALBUM: 50d4382c-ae8b-4ec3-a181-2b832f13829a
      KIOSK_IMAGE_FIT: CONTAIN
      KIOSK_BACKGROUND_BLUR: TRUE
      KIOSK_TRANSITION: NONE
      KIOSK_SHOW_PROGRESS: TRUE
      KIOSK_SHOW_IMAGE_TIME: FALSE
      KIOSK_SHOW_IMAGE_DATE: FALSE
      KIOSK_CACHE: TRUE
      KIOSK_SHOW_IMAGE_LOCATION: FALSE
      KIOSK_SLEEP_START: 22
      KIOSK_SLEEP_END: 8
    ports:
      - 3001:3000
    restart: on-failure
```

**Any parms passed to the URL used to access Kiosk**
None

**Desktop:**
Firefox 132.0 (64-bit)

**Smartphone:**
Home Assistant 2024.11 iFrame

**Additional context**
None

**Comment by joelis10** [comment]
that works for now, thank you. I was also wondering: is there an official way to move the time and date, also perhaps with CSS? As I said, I use this on my smart clock and the Google "mute" icon is up in the top right, making the aforementioned hard to read.

**Comment by damongolding** [comment]
> that works for now, thank you. I was also wondering: is there an official way to move the time and date, also perhaps with CSS? As I said, I use this on my smart clock and the Google "mute" icon is up in the top right, making the aforementioned hard to read.

I assume you mean outside of sleep mode?

**Comment by joelis10** [comment]
Yes, although I think I found a solution myself that works well enough for now:
```
# clock {
    position: fixed;
    bottom: 0;
}
```

Doesn't mess with sleep mode but the text shadow cuts off a bit abruptly at the top. Something I'll fix another day, as it's late for me here in the UK

**Comment by damongolding** [comment]
I can work something up to move it where you want but it depends on which layout you're using as elements move around depending on that. I'm UK based too so I'm off to bed also 🛌
