### ISSUE TITLE
Can't seem to get the 'X' to disappear

### ISSUE THREAD

**Issue by jaraeez** [damongolding/immich-kiosk#198]
**Describe the bug**
Running kiosk on an iPad (same issue on different variety iPads) there is an 'X' on the top left that does not disappear

**To Reproduce**
1. Open safari & type address
2. Tap to get full screen option
3. Goes in full screen
4. After a short while options disappear except the'X'

**Expected behavior**
The 'X' should also disappear

**Screenshots**
![IMG_4863](https://github.com/user-attachments/assets/e2d56112-f4b1-4c5c-beb4-90f27f2e402e)

**Your Kiosk version**
0.13.0

**Your Kiosk installation**
- Docker

**Your Kiosk ENV or config file**

**Additional context**

**Comment by damongolding** [comment]
That’s not part of Kiosk’s UI. It must be a IOS button to exit full screen.

**Comment by jaraeez** [comment]
Ok, thanks for the heads up
