### ISSUE TITLE
Portrait photos often shown in landscape

### ISSUE THREAD

**Issue by McTristan** [damongolding/immich-kiosk#214]
**Describe the bug**

In the immich app and website all the photos are shown in the correct orientation, the EXIF data also seems to be correct and every program shows the files as portrait files. However in immich kiosk they are shown as landscape. I've attached one of the files.

The EXIF Information states:

Orientation | Rotate 270 CW

The width and height also seems to be correct. It is 2592 (w) x 1944 (h) - rotate that by 270 degrees clockwise and you should end up with a portrait photo not a landscape photo or am I'm mistaken?

As I said, the pictures are shown correctly in the iOS and WebApp but not in kiosk.

Any ideas?

![20160801_105837](https://github.com/user-attachments/assets/6d04f369-021e-4308-aa04-129e8123cafb)

**Comment by damongolding** [comment]
Are you using `use_original_image` set to true?

There is an open pull request to fix this issue with original images.

**Comment by McTristan** [comment]
Yes. I’m using a high resolution display and the images look much better.
Am 8. Dez. 2024, 22:16 +0100 schrieb Damon ***@***.***>:

**Comment by damongolding** [comment]
Ahh ok. So it's a known issue that will be patched soon 😊

**Comment by McTristan** [comment]
I'm trying it right now! Thank you!

**Comment by McTristan** [comment]
Seems to work. I'll keep an eye on it ;)
