### ISSUE TITLE
max number of images

### ISSUE THREAD

**Issue by nocomment-bln** [damongolding/immich-kiosk#234]
Hello,
I have around 3200 images in an album to display via immich-kiosk.

Is that possible ?

I am asking because KIOSK_FETCHED_ASSETS_SIZE has maximum 1000.

Thanks for your help, awesome project!

**Comment by damongolding** [comment]
That's not a problem at all. 1000 is the max limit that the Immich Api allows.

The `KIOSK_FETCHED_ASSETS_SIZE` defines how many assets Kiosk fetches at a time. It will then chip away at those until there are no more valid assets then grab more.

**Comment by nocomment-bln** [comment]
Hello ) Thanks.

I have around 2k images in one album, but the immich kiosk instance (the latest) seems not to show all images.

I always see the same images.

**Comment by damongolding** [comment]
Can you provide your compose and your (if you use one) config file with sensitive data removed?

**Comment by nocomment-bln** [comment]
Sure!

`
services:
  immich-kiosk:
    image: damongolding/immich-kiosk:latest
    container_name: immich-kiosk
    environment:
      TZ: "Europe/Berlin"
      # Required settings
      KIOSK_IMMICH_API_KEY: "7pVQ8B****ShY"
      KIOSK_IMMICH_URL: "http://****:2283"
      # External url for image links/QR codes
      KIOSK_IMMICH_EXTERNAL_URL: ""
      # Clock
      KIOSK_SHOW_TIME: false
      KIOSK_TIME_FORMAT: 24
      KIOSK_SHOW_DATE: false
      KIOSK_DATE_FORMAT: DD.MM.YYYY
      # Kiosk behaviour
      KIOSK_REFRESH: 70
      KIOSK_DISABLE_SCREENSAVER: true
      KIOSK_OPTIMIZE_IMAGES: false
      # Asset sources
      KIOSK_SHOW_ARCHIVED: false
      KIOSK_ALBUM: "8ad5***a86932b24c"
      KIOSK_EXCLUDED_ALBUMS: "ALBUM_ID,ALBUM_ID,ALBUM_ID"
      KIOSK_PERSON: "PERSON_ID,PERSON_ID,PERSON_ID"
      # UI
      KIOSK_DISABLE_UI: false
      KIOSK_FRAMELESS: false
      KIOSK_HIDE_CURSOR: false
      KIOSK_FONT_SIZE: 100
      KIOSK_BACKGROUND_BLUR: true
      KIOSK_THEME: fade
      KIOSK_LAYOUT: splitview
      # Sleep mode
      # KIOSK_SLEEP_START: 22
      # KIOSK_SLEEP_END: 7
      # Transition options
      KIOSK_TRANSITION: none
      KIOSK_FADE_TRANSITION_DURATION: 1
      KIOSK_CROSS_FADE_TRANSITION_DURATION: 1
      # Image display settings
      KIOSK_SHOW_PROGRESS: false
      KIOSK_IMAGE_FIT: none
      KIOSK_IMAGE_EFFECT: smart-zoom
      KIOSK_IMAGE_EFFECT_AMOUNT: 100
      KIOSK_USE_ORIGINAL_IMAGE: false
      # Image metadata
      KIOSK_SHOW_IMAGE_TIME: false
      KIOSK_IMAGE_TIME_FORMAT: 24
      KIOSK_SHOW_IMAGE_DATE: false
      KIOSK_IMAGE_DATE_FORMAT: YYYY-MM-DD
      KIOSK_SHOW_IMAGE_DESCRIPTION: false
      KIOSK_SHOW_IMAGE_EXIF: false
      KIOSK_SHOW_IMAGE_LOCATION: false
      KIOSK_HIDE_COUNTRIES: "HIDDEN_COUNTRY,HIDDEN_COUNTRY"
      KIOSK_SHOW_IMAGE_ID: false
      KIOSK_SHOW_MORE_INFO: true
      KIOSK_SHOW_MORE_INFO_IMAGE_LINK: true
      KIOSK_SHOW_MORE_INFO_QR_CODE: true
      # Kiosk settings
      KIOSK_WATCH_CONFIG: false
      KIOSK_FETCHED_ASSETS_SIZE: 1000
      KIOSK_HTTP_TIMEOUT: 20
      KIOSK_PASSWORD: ""
      KIOSK_CACHE: true
      KIOSK_PREFETCH: true
      KIOSK_ASSET_WEIGHTING: true
      KIOSK_PORT: 4000
    ports:
      - 4000:4000
    restart: always
    labels:
      com.centurylinklabs.watchtower.enable: "true"`

**Comment by nocomment-bln** [comment]
Do you had have time to check my compose file ?

**Comment by nocomment-bln** [comment]
thank you sir :)
