### ISSUE TITLE
Cant query multiple albums with URL query

### ISSUE THREAD

**Issue by tal-sitton** [damongolding/immich-kiosk#238]
**Describe the bug**
When using multiple albums with URL query, only the last one is used.

**To Reproduce**
1. Go to http://{URL}?album=ALBUM_ID1&album=ALBUM_ID2
2. The images are only from the last album specified (ALBUM_ID2)

**Expected behavior**
random images from **both** of the albums

**Your Kiosk version**
0.14.5

**Your Kiosk installation**
- Docker

**Your Kiosk ENV or config file**
any config

**Any parms passed to the URL used to access Kiosk**
- http://{URL}?album=ALBUM_ID1&album=ALBUM_ID2

**Additional context**
The frontend is kind of a blackbox to me (I don't know templ) so I really don't know the cause of the problem,
but I did open Chrome dev tools, and found that in the post to `/image` the browser only sends one album, and not all of them

**Comment by damongolding** [comment]
This issue has been fixed in 0.14.6 and will be released shortly 😊

**Comment by damongolding** [comment]
Yeah in essence js was overwriting the params instead of appending them.
