### ISSUE TITLE
Homeassistant screensaver?

### ISSUE THREAD

**Issue by brayStorm** [damongolding/immich-kiosk#38]
I have this all set up and working perfect.
Does anyone have any examples on how to make this pop up as a screensaver? Wallpanel doesn't allow me to have a pop-up webpage, and I'm struggling getting it to work right.

**Comment by damongolding** [comment]
Do you have a screensaver already set up in HA?

**Comment by brayStorm** [comment]
I figured it out with wallpanel.

`wallpanel:
  enabled: true
  image_fit: cover
  idle_time: 10
  screensaver_entity: input_boolean.kiosk
  screensaver_stop_navigation_path: /dashboard-kiosk
  fullscreen: true
  display_time: 86400
  image_url: >-
    http://{immich-kiosk-url}?image_fit=cover&transition=fade&person=PERSON_1_ID&person=PERSON_2_ID
  cards:
    - type: vertical-stack
      cards:
        - type: custom:weather-card
          details: true
          forecast: true
          hourly_forecast: false
          name: Weather
          entity: weather.pirateweather
          current: true
          number_of_forecasts: '6'
        - type: custom:horizon-card
          darkMode: true
          showAzimuth: true
          showElevation: true
`

**Comment by damongolding** [comment]
If you have the time I would really appreciate this example being added to the examples in the README. No worries if you don't though 😊

**Comment by brayStorm** [comment]
Done!

**Comment by srvoets** [comment]
Can you do this for an album?  if I use ?album=ALBUMID in my browser, I get a slideshow, but it will not work as an image_url in wallpanel.

If I do ?image&album=ALBUMID it displays one image on wallpanel, but will not ever change.

**Comment by damongolding** [comment]
I think in this example @srvoets they are not using the /image endpoint. Your the url you would use would be `http://YOUR_KIOSK_URL?album=ALBUM_ID`.

**Comment by srvoets** [comment]
> I think in this example @srvoets they are not using the /image endpoint. So the url you would use would be `http://YOUR_KIOSK_URL?album=ALBUM_ID`.
> 
> The /image endpoint only displays one image, the onus is on the fetcher to repeatedly call this endpoint.

This is exactly what I am doing, http://***:3050/?album=ABCD123

It displays 0 pictures, just a blank flashing screen on my devices.

If I go to that URL in my web browser, it displays the slideshow as expected.

**Comment by damongolding** [comment]
Are you accessing Home Assistant via https but trying to access Kioks via http? I know that is an issue. 

Maybe @brayStorm could possible help you?

As I stated on the ReadMe, I can't really support issues on Home Assistant as I haven't tested Kiosk on it.

**Comment by srvoets** [comment]
> Are you accessing Home Assistant via https but trying to access Kiosk via http? I know that is an issue.
> 
> Maybe @brayStorm could possible help you?
> 
> As I stated on the ReadMe, I can't really support issues on Home Assistant as I haven't tested Kiosk on it.

I totally get it, I just came here to see if any other HA user was experiencing this, or to see another users known-good configs.

Ever since the google image API was deprecated, I migrated to immich, and  Ive been looking for a replacement for it for my fully-kiosk devices, and the immich integration 'works' but also crashes my devices a few times a day, but it restarts itself and continues.

But then I found your app and ran it in docker and its basically exactly what I want, I love being able to use one container for multiple devices, I just need to make it work.

I am passing an http url to as my fully kiosk start page as well as on a pi\touchscreen chromium kiosk, so that is HTTP, and the URL I am using looks like this, when I put this URL into my browser on PC, it behaves as expected.  

`screensaver_entity: input_boolean.panel_screensaver
  image_url: >-
    http://[IP]:3050/?album=[ALBUMID]
  show_image_info: false`

I have also tried this, which oddly enough, worked the first time, but obvioulsy was not a "slideshow" but ever since I changed the url once, it has been displaying a black box, and I occasionally see the "broken picture" icon in the top left in between flashes.  


`screensaver_entity: input_boolean.panel_screensaver
  image_url: >-
    http://[IP]:3050/image&album=[ALBUMID]
  show_image_info: false`


So yes, I am using local http between them on HA, and my kiosk devices and my immich-kiosk container.

**Comment by srvoets** [comment]
> > Are you accessing Home Assistant via https but trying to access Kiosk via http? I know that is an issue.
> > Maybe @brayStorm could possible help you?
> > As I stated on the ReadMe, I can't really support issues on Home Assistant as I haven't tested Kiosk on it.
> 
> I totally get it, I just came here to see if any other HA user was experiencing this, or to see another users known-good configs.
> 
> Ever since the google image API was deprecated, I migrated to immich, and Ive been looking for a replacement for it for my fully-kiosk devices, and the immich integration 'works' but also crashes my devices a few times a day, but it restarts itself and continues.
> 
> But then I found your app and ran it in docker and its basically exactly what I want, I love being able to use one container for multiple devices, I just need to make it work.
> 
> I am passing an http url to as my fully kiosk start page as well as on a pi\touchscreen chromium kiosk, so that is HTTP, and the URL I am using looks like this, when I put this URL into my browser on PC, it behaves as expected.
> 
> `screensaver_entity: input_boolean.panel_screensaver image_url: >- http://[IP]:3050/?album=[ALBUMID] show_image_info: false`
> 
> I have also tried this, which oddly enough, worked the first time, but obvioulsy was not a "slideshow" but ever since I changed the url once, it has been displaying a black box, and I occasionally see the "broken picture" icon in the top left in between flashes.
> 
> `screensaver_entity: input_boolean.panel_screensaver image_url: >- http://[IP]:3050/image&album=[ALBUMID] show_image_info: false`
> 
> So yes, I am using local http between them on HA, and my kiosk devices and my immich-kiosk container.

I just want to say I decided to simplify things, on the device running fully kiosk I removed wallpanel from my config, and set the URL to the screensaver in fully kiosk and it works exactly as expected.

I cant overlay lovelace cards, but for me that is OK.

I still have to sort out another solution for the Pi, however.

**Comment by damongolding** [comment]
So I took another look at the example of the readme. They are using the /image endpoint. I assume you have tried adding all the other keys from the example? as it looks to include a timer/refresh value.

**Comment by damongolding** [comment]
So I install wallpanel and added the below and it works just fine:

```yaml
wallpanel:
  enabled: true
  image_fit: cover
  idle_time: 10
  screensaver_entity: input_boolean.kiosk
  screensaver_stop_navigation_path: /dashboard-kiosk
  fullscreen: true
  display_time: 10
  image_url: http://KIOSK_IP:3000/image?album=shared
```

**Comment by srvoets** [comment]
> So I install wallpanel and added the below and it works just fine:
> 
> ```yaml
> wallpanel:
>   enabled: true
>   image_fit: cover
>   idle_time: 10
>   screensaver_entity: input_boolean.kiosk
>   screensaver_stop_navigation_path: /dashboard-kiosk
>   fullscreen: true
>   display_time: 10
>   image_url: http://KIOSK_IP:3000/image?album=shared
> ```



Thanks for going out of your way to test this for me, I am re-building my pi kiosk as I type this and will test it out shortly.

Should above config work for an album?

**Comment by damongolding** [comment]
Does the above not change the image every 10 seconds?

**Comment by srvoets** [comment]
> Does the above not change the image every 10 seconds?

Negative, and if I access that URL from my web browser, it is not a slideshow either, this is the URL I am using inside FullyKiosk, and it works in Fully Kiosk and my desktop browser as a slideshow:

/?album="[ALBUM_ID]"

**Comment by damongolding** [comment]
The `/image` endpoint only serves up one image per request, so if you visit it in your browser you wont see a slideshow. If you hit refresh you should see new images.

I made that endpoint for other services to utilise Kiosk's filtering. So the above is telling wallpanel to fetch a new image every 10 seconds. 

* Try clearing the browser cache or restarting the device if you can't clear the cache.
* If it's still not working as expected try viewing the browser console log (if you are able) for any errors.

**Comment by gytisgreitai** [comment]
And the image endpoint won't have any custom attributes, just pure image?

**Comment by damongolding** [comment]
It accepts all the same url queries but not all will apply/work e.g. `image_fit`

**Comment by gytisgreitai** [comment]
This native approach is nice, but it has it's limitations - basically that you don't get the nice features from the Immich Kiosk - discrete photo location and weather component + amazing splitview. So I did a bit of an different approach.

Created this javascript which basically adds an iframe and renders the Immich Kiosk in full width:
```javascript
// URL of the iframe to be displayed
const iframeUrl = 'https://{kiosk_url}/?image_fit=cover&show_image_location=true&show_image_exif=false&refresh=1800&show_more_info=true&show_album_name=true&frameless=true&image_date_format=YYYY%20MMMM&layout=splitview&weather=some_location';
const idlePeriodTimeInMs = 5 * 60 * 1000; // 5 minutes

// Create an iframe element
const iframe = document.createElement('iframe');
iframe.src = iframeUrl;
iframe.style.position = 'fixed';
iframe.style.top = '0';
iframe.style.left = '0';
iframe.style.width = '100%';
iframe.style.height = '100%';
iframe.style.border = 'none';
iframe.style.zIndex = '9998';
iframe.style.backgroundColor = 'black';
iframe.style.display = 'none'; 

// Create an invisible overlay element which will dismiss the iframe when clicked
const overlay = document.createElement('div');
overlay.style.position = 'fixed';
overlay.style.top = '0';
overlay.style.left = '0';
overlay.style.width = '100%';
overlay.style.height = '100%';
overlay.style.zIndex = '9999';
overlay.style.backgroundColor = 'rgba(0, 0, 0, 0)'; 
overlay.style.display = 'none'; 


document.body.appendChild(iframe);
document.body.appendChild(overlay);

function showSlideshow() {
    iframe.style.display = 'block';
    overlay.style.display = 'block';
    document.body.style.overflow = 'hidden';
}

function hideSlideshow() {
    iframe.style.display = 'none';
    overlay.style.display = 'none';
    document.body.style.overflow = '';
}

overlay.addEventListener('click', hideSlideshow);
overlay.addEventListener('keypress', hideSlideshow);
overlay.addEventListener('touchstart', hideSlideshow);

let inactivityTimeout;

function resetInactivityTimer() {
    clearTimeout(inactivityTimeout);
    iframe.style.display = 'none'; 
    overlay.style.display = 'none'; 
    document.body.style.overflow = '';
    inactivityTimeout = setTimeout(hideSlideshow, idlePeriodTimeInMs);
}

// my Kiosk is running on Windows 10 with Edge browser, so run only there
if (/Edg/.test(navigator.userAgent)) {
    document.addEventListener('click', resetInactivityTimer);
    document.addEventListener('keypress', resetInactivityTimer);
    document.addEventListener('touchstart', resetInactivityTimer);

    resetInactivityTimer();
}
```

Saved this into `www/immich-kiosk-fullscreen.js`
And added it to `configuration.yaml`:

```
lovelace:
  mode: yaml
  resources:
    - url: /local/immich-kiosk-fullscreen.js
       type: js
```

**Comment by damongolding** [comment]
Nice!

Though I can't see if showSlideshow is ever called? also you could listen for mouse movement to reset to maybe?

**Comment by gytisgreitai** [comment]
Good catch, tried to cleanup before posting, mised some parts

This runs on a touchscreen so for me no need for mouse events, but sure, why not. Just I guess then some kind of debouncing would be useful

**Comment by damongolding** [comment]
If it works for you non need to add the unneeded mouse listener.

You could reuse the hideSlideshow() func here too. 

```JavaScript

function resetInactivityTimer() {
    clearTimeout(inactivityTimeout);
    hideSlideshow();
    inactivityTimeout = setTimeout(showSlideshow, idlePeriodTimeInMs);
}

```
