### ISSUE TITLE
Shows photos that are archived

### ISSUE THREAD

**Issue by kfoxton** [damongolding/immich-kiosk#40]
When no specific album, or person is defined, it shows photos that are marked as archive, as well as the normal pictures.  I generally use archive to remove documents and other personal photos that I don't want to be in the normal photo timeline from beinf displayed. It was unexpected that they show up in the kiosk.

Expected: to not sure photos that are archived.

**Comment by damongolding** [comment]
Thanks for submitting.

That’s unexpected behaviour and I will patch it.
