### ISSUE TITLE
Show Image location below image date and time

### ISSUE THREAD

**Issue by bladecell** [damongolding/immich-kiosk#59]
Add option to show image location based on location data of image.

**Comment by damongolding** [comment]
This is on my roadmap already 😊

**Comment by damongolding** [comment]
![image](https://github.com/user-attachments/assets/88fca150-e4f3-4143-a097-8f48263f2e40)

Something like this?

**Comment by damongolding** [comment]
Added in 0.8.0

**Comment by bladecell** [comment]
Fantastic, thanks 😎
