### ISSUE TITLE
No connection symbol appears off page and makes the page larger than the screen

### ISSUE THREAD

**Issue by joelis10** [damongolding/immich-kiosk#6]
I'm trying to implement this project as an iframe card in Home Assistant, but one thing annoying me is that the iframe is scrollable because of the no connection symbol appearing off view.
![image](https://github.com/user-attachments/assets/fdc25e10-86de-4a0b-9cfb-213c3e439f45)
Above is the symbol I'm talking about, once this is fixed the project will be perfect for me to use

**Comment by damongolding** [comment]
Yes, this was a oversight on my part. I fixed that in 0.2.0. But please do check out the release notes for [0.2.0](https://github.com/damongolding/immich-kiosk/releases/tag/v0.2.0) as I had to make some breaking changes from 0.1.x

**Comment by joelis10** [comment]
are you sure the issue was fixed? I've just updated and it's still there, possibly worse than before as there's an extra blank gap above it now

**Comment by damongolding** [comment]
I am. It may be a caching issue as it was a css fix. Try hard reloading the page or try incognito mode. I may have to implement cache busting 🤔

**Comment by joelis10** [comment]
You may be correct, as a new device I've tried just now doesn't show it. I'm not entirely sure how I'll clean cache inside the HA app on my other device but good to know it's just my end

________________________________

**Comment by damongolding** [comment]
I will add css cache busting so this shouldn’t be an issue going forward.The update in theory should fix the issue on your devices but failing that maybe a reboot of them might flush the cache?
