### ISSUE TITLE
Password URL param not working

### ISSUE THREAD

**Issue by FjellOverflow** [damongolding/immich-kiosk#62]
**Describe the bug**
When setting `KIOSK_PASSWORD: "test123"` in ENV, the frontent always gets `401` response even though the `password` URL-param is set. All works fine when no password set in `ENV`.

**To Reproduce**
- Start container with `KIOSK_PASSWORD: "test123"`
- Access `http://localhost:3000/?password=test123` in browser.

**Expected behavior**
Can access webapp.

**Your Kiosk version**
0.7.1

**Your Kiosk installation**
 Docker

**The URL used to access Kiosk**
[- http://{KIOSK_URL}/show_time=true&time_format=12
](http://localhost:3000/?password=test123)

**Desktop:**
 - OS: Linux
 - Browser: any

**Comment by damongolding** [comment]
Excellent find.

This is because the moved the method from GET to POST and even though the "password" is set via a url query, it is now sent via form data but Kiosk is still look for it in the queries.

**Comment by damongolding** [comment]
Should be fixed in 0.7.2 now
