### ISSUE TITLE
Setting show_progress: true in the config.yaml produces fatal error "Immich Url is missing"

### ISSUE THREAD

**Issue by EricSoldierer** [damongolding/immich-kiosk#68]
**Describe the bug**
As soon as the line `show_progress: true` is added to the config.yaml file, the server wont start and logs show a fatal error `Immich Url is missing`. Uncommenting or removing only this line solves the error.

**To Reproduce**
1. Have a config.yaml file without show_progress
2. add show_progress: true
3. restart service
4.  read logs

**Your Kiosk version**
0.8.0

**Your Kiosk installation**
- Docker

**Comment by damongolding** [comment]
That sounds really odd. I will have to run a test when I'm back behind my computer.

**Comment by damongolding** [comment]
Ok so I can reproduce the error by uncommenting `#show_progress: true`.

The issues is cause because you have two `show_progress` entries. One at line 18 and one at 24.

Delete one and then set the other to your desired option  (true | false)

**Comment by EricSoldierer** [comment]
Oh wow.. thanks man
